name = "FlightMechanicsSimulator"
uuid = "f4210329-0d58-4a8c-9620-f0228abde670"
authors = ["Alex Saez <saezm.alex@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
